export const colors = [
    { letter: "A", color: "#FF3232" },
    { letter: "B", color: "#FF7C32" },
    { letter: "C", color: "#FFC632" },
    { letter: "D", color: "#E2FF32" },
    { letter: "E", color: "#A5FF32" },
    { letter: "F", color: "#68FF32" },
    { letter: "G", color: "#32FF53" },
    { letter: "H", color: "#32FF90" },
    { letter: "I", color: "#32FFDA" },
    { letter: "J", color: "#32CEFF" },
    { letter: "K", color: "#3278FF" },
    { letter: "L", color: "#3247FF" },
    { letter: "M", color: "#5B32FF" },
    { letter: "N", color: "#8C32FF" },
    { letter: "O", color: "#BE32FF" },
    { letter: "P", color: "#FB32FF" },
    { letter: "Q", color: "#FF32C6" },
    { letter: "R", color: "#FF327C" },
    { letter: "S", color: "#FF3257" },
    { letter: "T", color: "#BF5C00" },
    { letter: "U", color: "#BBBF00" },
    { letter: "V", color: "#49BF00" },
    { letter: "W", color: "#00BF4D" },
    { letter: "X", color: "#00A8BF" },
    { letter: "Y", color: "#0036BF" },
    { letter: "Z", color: "#6B00BF" },
]