import type { NextPage } from "next";
import Head from "next/head";
import Admin from "./admin"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>My Rapid Chef</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon_256x256.png" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <Admin />
    </div>
  );
};

export default Home;
